// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "mylcm_lidarObjInfor.h"

static int __mylcm_lidarObjInfor_hash_computed;
static uint64_t __mylcm_lidarObjInfor_hash;

uint64_t __mylcm_lidarObjInfor_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __mylcm_lidarObjInfor_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__mylcm_lidarObjInfor_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x06e4f90a1ec34dc4LL
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __mylcm_lidarObjInfor_get_hash(void)
{
    if (!__mylcm_lidarObjInfor_hash_computed) {
        __mylcm_lidarObjInfor_hash = (int64_t)__mylcm_lidarObjInfor_hash_recursive(NULL);
        __mylcm_lidarObjInfor_hash_computed = 1;
    }

    return __mylcm_lidarObjInfor_hash;
}

int __mylcm_lidarObjInfor_encode_array(void *buf, int offset, int maxlen, const mylcm_lidarObjInfor *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].trackId0), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].speed0), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].age0), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].dist0), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].orient0), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].contourHeight0), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].contour0, 8);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int mylcm_lidarObjInfor_encode(void *buf, int offset, int maxlen, const mylcm_lidarObjInfor *p)
{
    int pos = 0, thislen;
    int64_t hash = __mylcm_lidarObjInfor_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __mylcm_lidarObjInfor_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __mylcm_lidarObjInfor_encoded_array_size(const mylcm_lidarObjInfor *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int16_t_encoded_array_size(&(p[element].trackId0), 1);

        size += __int16_t_encoded_array_size(&(p[element].speed0), 1);

        size += __int16_t_encoded_array_size(&(p[element].age0), 1);

        size += __int16_t_encoded_array_size(&(p[element].dist0), 1);

        size += __int16_t_encoded_array_size(&(p[element].orient0), 1);

        size += __int16_t_encoded_array_size(&(p[element].contourHeight0), 1);

        size += __int16_t_encoded_array_size(p[element].contour0, 8);

    }
    return size;
}

int mylcm_lidarObjInfor_encoded_size(const mylcm_lidarObjInfor *p)
{
    return 8 + __mylcm_lidarObjInfor_encoded_array_size(p, 1);
}

int __mylcm_lidarObjInfor_decode_array(const void *buf, int offset, int maxlen, mylcm_lidarObjInfor *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].trackId0), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].speed0), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].age0), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].dist0), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].orient0), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].contourHeight0), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].contour0, 8);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __mylcm_lidarObjInfor_decode_array_cleanup(mylcm_lidarObjInfor *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int16_t_decode_array_cleanup(&(p[element].trackId0), 1);

        __int16_t_decode_array_cleanup(&(p[element].speed0), 1);

        __int16_t_decode_array_cleanup(&(p[element].age0), 1);

        __int16_t_decode_array_cleanup(&(p[element].dist0), 1);

        __int16_t_decode_array_cleanup(&(p[element].orient0), 1);

        __int16_t_decode_array_cleanup(&(p[element].contourHeight0), 1);

        __int16_t_decode_array_cleanup(p[element].contour0, 8);

    }
    return 0;
}

int mylcm_lidarObjInfor_decode(const void *buf, int offset, int maxlen, mylcm_lidarObjInfor *p)
{
    int pos = 0, thislen;
    int64_t hash = __mylcm_lidarObjInfor_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __mylcm_lidarObjInfor_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int mylcm_lidarObjInfor_decode_cleanup(mylcm_lidarObjInfor *p)
{
    return __mylcm_lidarObjInfor_decode_array_cleanup(p, 1);
}

int __mylcm_lidarObjInfor_clone_array(const mylcm_lidarObjInfor *p, mylcm_lidarObjInfor *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int16_t_clone_array(&(p[element].trackId0), &(q[element].trackId0), 1);

        __int16_t_clone_array(&(p[element].speed0), &(q[element].speed0), 1);

        __int16_t_clone_array(&(p[element].age0), &(q[element].age0), 1);

        __int16_t_clone_array(&(p[element].dist0), &(q[element].dist0), 1);

        __int16_t_clone_array(&(p[element].orient0), &(q[element].orient0), 1);

        __int16_t_clone_array(&(p[element].contourHeight0), &(q[element].contourHeight0), 1);

        __int16_t_clone_array(p[element].contour0, q[element].contour0, 8);

    }
    return 0;
}

mylcm_lidarObjInfor *mylcm_lidarObjInfor_copy(const mylcm_lidarObjInfor *p)
{
    mylcm_lidarObjInfor *q = (mylcm_lidarObjInfor*) malloc(sizeof(mylcm_lidarObjInfor));
    __mylcm_lidarObjInfor_clone_array(p, q, 1);
    return q;
}

void mylcm_lidarObjInfor_destroy(mylcm_lidarObjInfor *p)
{
    __mylcm_lidarObjInfor_decode_array_cleanup(p, 1);
    free(p);
}

int mylcm_lidarObjInfor_publish(lcm_t *lc, const char *channel, const mylcm_lidarObjInfor *p)
{
      int max_data_size = mylcm_lidarObjInfor_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = mylcm_lidarObjInfor_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _mylcm_lidarObjInfor_subscription_t {
    mylcm_lidarObjInfor_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void mylcm_lidarObjInfor_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    mylcm_lidarObjInfor p;
    memset(&p, 0, sizeof(mylcm_lidarObjInfor));
    status = mylcm_lidarObjInfor_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding mylcm_lidarObjInfor!!!\n", status);
        return;
    }

    mylcm_lidarObjInfor_subscription_t *h = (mylcm_lidarObjInfor_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    mylcm_lidarObjInfor_decode_cleanup (&p);
}

mylcm_lidarObjInfor_subscription_t* mylcm_lidarObjInfor_subscribe (lcm_t *lcm,
                    const char *channel,
                    mylcm_lidarObjInfor_handler_t f, void *userdata)
{
    mylcm_lidarObjInfor_subscription_t *n = (mylcm_lidarObjInfor_subscription_t*)
                       malloc(sizeof(mylcm_lidarObjInfor_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 mylcm_lidarObjInfor_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg mylcm_lidarObjInfor LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int mylcm_lidarObjInfor_subscription_set_queue_capacity (mylcm_lidarObjInfor_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int mylcm_lidarObjInfor_unsubscribe(lcm_t *lcm, mylcm_lidarObjInfor_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe mylcm_lidarObjInfor_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

