// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _mylcm_lidarObjInfor_h
#define _mylcm_lidarObjInfor_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _mylcm_lidarObjInfor mylcm_lidarObjInfor;
struct _mylcm_lidarObjInfor
{
    int16_t    trackId0;
    int16_t    speed0;
    int16_t    age0;
    int16_t    dist0;
    int16_t    orient0;
    int16_t    contourHeight0;
    int16_t    contour0[8];
};

/**
 * Create a deep copy of a mylcm_lidarObjInfor.
 * When no longer needed, destroy it with mylcm_lidarObjInfor_destroy()
 */
mylcm_lidarObjInfor* mylcm_lidarObjInfor_copy(const mylcm_lidarObjInfor* to_copy);

/**
 * Destroy an instance of mylcm_lidarObjInfor created by mylcm_lidarObjInfor_copy()
 */
void mylcm_lidarObjInfor_destroy(mylcm_lidarObjInfor* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _mylcm_lidarObjInfor_subscription_t mylcm_lidarObjInfor_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * mylcm_lidarObjInfor is received.
 */
typedef void(*mylcm_lidarObjInfor_handler_t)(const lcm_recv_buf_t *rbuf,
             const char *channel, const mylcm_lidarObjInfor *msg, void *userdata);

/**
 * Publish a message of type mylcm_lidarObjInfor using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
int mylcm_lidarObjInfor_publish(lcm_t *lcm, const char *channel, const mylcm_lidarObjInfor *msg);

/**
 * Subscribe to messages of type mylcm_lidarObjInfor using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message is received.
 *                This function is invoked by LCM during calls to lcm_handle() and
 *                lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return 0 on success, <0 if an error occured
 */
mylcm_lidarObjInfor_subscription_t* mylcm_lidarObjInfor_subscribe(lcm_t *lcm, const char *channel, mylcm_lidarObjInfor_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by mylcm_lidarObjInfor_subscribe()
 */
int mylcm_lidarObjInfor_unsubscribe(lcm_t *lcm, mylcm_lidarObjInfor_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
int mylcm_lidarObjInfor_subscription_set_queue_capacity(mylcm_lidarObjInfor_subscription_t* subs,
                              int num_messages);

/**
 * Encode a message of type mylcm_lidarObjInfor into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to mylcm_lidarObjInfor_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int mylcm_lidarObjInfor_encode(void *buf, int offset, int maxlen, const mylcm_lidarObjInfor *p);

/**
 * Decode a message of type mylcm_lidarObjInfor from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with mylcm_lidarObjInfor_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int mylcm_lidarObjInfor_decode(const void *buf, int offset, int maxlen, mylcm_lidarObjInfor *msg);

/**
 * Release resources allocated by mylcm_lidarObjInfor_decode()
 * @return 0
 */
int mylcm_lidarObjInfor_decode_cleanup(mylcm_lidarObjInfor *p);

/**
 * Check how many bytes are required to encode a message of type mylcm_lidarObjInfor
 */
int mylcm_lidarObjInfor_encoded_size(const mylcm_lidarObjInfor *p);

// LCM support functions. Users should not call these
int64_t __mylcm_lidarObjInfor_get_hash(void);
uint64_t __mylcm_lidarObjInfor_hash_recursive(const __lcm_hash_ptr *p);
int __mylcm_lidarObjInfor_encode_array(void *buf, int offset, int maxlen, const mylcm_lidarObjInfor *p, int elements);
int __mylcm_lidarObjInfor_decode_array(const void *buf, int offset, int maxlen, mylcm_lidarObjInfor *p, int elements);
int __mylcm_lidarObjInfor_decode_array_cleanup(mylcm_lidarObjInfor *p, int elements);
int __mylcm_lidarObjInfor_encoded_array_size(const mylcm_lidarObjInfor *p, int elements);
int __mylcm_lidarObjInfor_clone_array(const mylcm_lidarObjInfor *p, mylcm_lidarObjInfor *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
