// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "Point.h"

static int __Point_hash_computed;
static uint64_t __Point_hash;

uint64_t __Point_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __Point_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__Point_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0xabddc706ad074f64LL
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __Point_get_hash(void)
{
    if (!__Point_hash_computed) {
        __Point_hash = (int64_t)__Point_hash_recursive(NULL);
        __Point_hash_computed = 1;
    }

    return __Point_hash;
}

int __Point_encode_array(void *buf, int offset, int maxlen, const Point *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int Point_encode(void *buf, int offset, int maxlen, const Point *p)
{
    int pos = 0, thislen;
    int64_t hash = __Point_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __Point_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __Point_encoded_array_size(const Point *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int16_t_encoded_array_size(&(p[element].x), 1);

        size += __int16_t_encoded_array_size(&(p[element].y), 1);

    }
    return size;
}

int Point_encoded_size(const Point *p)
{
    return 8 + __Point_encoded_array_size(p, 1);
}

int __Point_decode_array(const void *buf, int offset, int maxlen, Point *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __Point_decode_array_cleanup(Point *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int16_t_decode_array_cleanup(&(p[element].x), 1);

        __int16_t_decode_array_cleanup(&(p[element].y), 1);

    }
    return 0;
}

int Point_decode(const void *buf, int offset, int maxlen, Point *p)
{
    int pos = 0, thislen;
    int64_t hash = __Point_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __Point_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int Point_decode_cleanup(Point *p)
{
    return __Point_decode_array_cleanup(p, 1);
}

int __Point_clone_array(const Point *p, Point *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int16_t_clone_array(&(p[element].x), &(q[element].x), 1);

        __int16_t_clone_array(&(p[element].y), &(q[element].y), 1);

    }
    return 0;
}

Point *Point_copy(const Point *p)
{
    Point *q = (Point*) malloc(sizeof(Point));
    __Point_clone_array(p, q, 1);
    return q;
}

void Point_destroy(Point *p)
{
    __Point_decode_array_cleanup(p, 1);
    free(p);
}

int Point_publish(lcm_t *lc, const char *channel, const Point *p)
{
      int max_data_size = Point_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = Point_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _Point_subscription_t {
    Point_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void Point_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    Point p;
    memset(&p, 0, sizeof(Point));
    status = Point_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding Point!!!\n", status);
        return;
    }

    Point_subscription_t *h = (Point_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    Point_decode_cleanup (&p);
}

Point_subscription_t* Point_subscribe (lcm_t *lcm,
                    const char *channel,
                    Point_handler_t f, void *userdata)
{
    Point_subscription_t *n = (Point_subscription_t*)
                       malloc(sizeof(Point_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 Point_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg Point LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int Point_subscription_set_queue_capacity (Point_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int Point_unsubscribe(lcm_t *lcm, Point_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe Point_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

