// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _Point_h
#define _Point_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _Point Point;
struct _Point
{
    int16_t    x;
    int16_t    y;
};

/**
 * Create a deep copy of a Point.
 * When no longer needed, destroy it with Point_destroy()
 */
Point* Point_copy(const Point* to_copy);

/**
 * Destroy an instance of Point created by Point_copy()
 */
void Point_destroy(Point* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _Point_subscription_t Point_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * Point is received.
 */
typedef void(*Point_handler_t)(const lcm_recv_buf_t *rbuf,
             const char *channel, const Point *msg, void *userdata);

/**
 * Publish a message of type Point using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
int Point_publish(lcm_t *lcm, const char *channel, const Point *msg);

/**
 * Subscribe to messages of type Point using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message is received.
 *                This function is invoked by LCM during calls to lcm_handle() and
 *                lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return 0 on success, <0 if an error occured
 */
Point_subscription_t* Point_subscribe(lcm_t *lcm, const char *channel, Point_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by Point_subscribe()
 */
int Point_unsubscribe(lcm_t *lcm, Point_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
int Point_subscription_set_queue_capacity(Point_subscription_t* subs,
                              int num_messages);

/**
 * Encode a message of type Point into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to Point_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int Point_encode(void *buf, int offset, int maxlen, const Point *p);

/**
 * Decode a message of type Point from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with Point_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int Point_decode(const void *buf, int offset, int maxlen, Point *msg);

/**
 * Release resources allocated by Point_decode()
 * @return 0
 */
int Point_decode_cleanup(Point *p);

/**
 * Check how many bytes are required to encode a message of type Point
 */
int Point_encoded_size(const Point *p);

// LCM support functions. Users should not call these
int64_t __Point_get_hash(void);
uint64_t __Point_hash_recursive(const __lcm_hash_ptr *p);
int __Point_encode_array(void *buf, int offset, int maxlen, const Point *p, int elements);
int __Point_decode_array(const void *buf, int offset, int maxlen, Point *p, int elements);
int __Point_decode_array_cleanup(Point *p, int elements);
int __Point_encoded_array_size(const Point *p, int elements);
int __Point_clone_array(const Point *p, Point *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
